#!/bin/sh

cd "$HOME"

git clone --bare "https://github.com/tlrobinson/dotfiles.git" "$HOME/.dotfiles.git"

alias config='/usr/bin/git --git-dir="$HOME/.dotfiles.git/" --work-tree="$HOME"'

config checkout
if [ $? = 0 ]; then
  echo "Checked out config.";
else
  echo "Backing up pre-existing dot files.";
  mkdir -p "$HOME/.dotfiles-backup"
  config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} "$HOME/.dotfiles-backup"/{}
fi;

config checkout
# config config status.showUntrackedFiles no

config submodule update --init
